[workspace]
members = ["wild", "wild_lib"]

resolver = "2"

[profile.dev]
debug = false

[profile.opt-debug]
inherits = "release"
debug = true

[patch.crates-io]
# TODO: Remove patch once version newer than 0.32.2 is released.
object = { git = "https://github.com/gimli-rs/object", rev = "1119a2a1fe8e089328c9634a01669a1da3383921" }
