[package]
name = "wild"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bytemuck = { version = "1.14.0", features = ["derive"] }
crossbeam-queue = "0.3.8"
crossbeam-utils = "0.8.18"
fxhash = "0.2.1"
memchr = "2.7.1"
memmap2 = "0.9.0"
object = { version = "0.32.1" }
rayon = "1.8.0"

[dev-dependencies]
ar = "0.9.0"
wait-timeout = "0.2.0"

[profile.dev]
debug = false

[profile.opt-debug]
inherits = "release"
debug = true

[patch.crates-io]
object = {path = "../../src/object"}
