[target.x86_64-unknown-linux-gnu]
#use cc from path which is usually linked to the favored one ?
#linker = "/usr/bin/clang-15"
# Might as well use the fastest available linker until we can self-link. Actually, we can now
# self-link, however until unwinding works, it's probably best to use a more mature linker.
#rustflags = ["-C", "link-arg=--ld-path=/usr/local/bin/mold"]


[target.x86_64-unknown-linux-musl]
linker = "/usr/bin/clang-15"
rustflags = [ "-C", "relocation-model=static", "-C", "link-arg=--ld-path=wild" ]

